
[project]
version = "0.1.0"
description = "Digital Committee Platform for Pakistani Communities"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.46.1",
    "psycopg2-binary>=2.9.10",
    "plotly>=6.2.0",
]
